# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: atlassian/default-image:3

pipelines:
  branches:
   main:
    - step: 
        name: Deploy to test
        deployment: test
        script:
          - pipe: microsoft/azure-static-web-apps-deploy:master
            variables:
                APP_LOCATION: '/angular-15-client'
                OUTPUT_LOCATION: '/angular-15-client/dist'
                API_TOKEN: '7386a45ae245497c5c358ac983d37872f7235da27ea3b4e29f5e7dda868ba5113-9d36d53b-074e-450f-9416-945f5d4b2a2f003234883'

          - echo "Your deployment to production script goes here..."
